# Generated by Django 2.1.2 on 2018-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_management_app', '0002_auto_20181029_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
